# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/switch_led.xdc

# Block Designs: bd/AES_CBC_128_design/AES_CBC_128_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design || ORIG_REF_NAME==AES_CBC_128_design} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_processing_system7_0_0/AES_CBC_128_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_processing_system7_0_0 || ORIG_REF_NAME==AES_CBC_128_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_AES_CBC_128_0_0/AES_CBC_128_design_AES_CBC_128_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_AES_CBC_128_0_0 || ORIG_REF_NAME==AES_CBC_128_design_AES_CBC_128_0_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_axi_dma_0_0/AES_CBC_128_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_axi_dma_0_0 || ORIG_REF_NAME==AES_CBC_128_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_axi_interconnect_0_0/AES_CBC_128_design_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_axi_interconnect_0_0 || ORIG_REF_NAME==AES_CBC_128_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_axi_interconnect_0_1/AES_CBC_128_design_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_axi_interconnect_0_1 || ORIG_REF_NAME==AES_CBC_128_design_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_axis_data_fifo_0_0/AES_CBC_128_design_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_axis_data_fifo_0_0 || ORIG_REF_NAME==AES_CBC_128_design_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_axis_data_fifo_0_1/AES_CBC_128_design_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_axis_data_fifo_0_1 || ORIG_REF_NAME==AES_CBC_128_design_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_rst_ps7_0_100M_0/AES_CBC_128_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==AES_CBC_128_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_xbar_0/AES_CBC_128_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_xbar_0 || ORIG_REF_NAME==AES_CBC_128_design_xbar_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_ps7_0_axi_periph_0/AES_CBC_128_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==AES_CBC_128_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_axi_gpio_0_0/AES_CBC_128_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_axi_gpio_0_0 || ORIG_REF_NAME==AES_CBC_128_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_auto_ds_0/AES_CBC_128_design_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_auto_ds_0 || ORIG_REF_NAME==AES_CBC_128_design_auto_ds_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_auto_pc_0/AES_CBC_128_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_auto_pc_0 || ORIG_REF_NAME==AES_CBC_128_design_auto_pc_0} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_auto_ds_1/AES_CBC_128_design_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_auto_ds_1 || ORIG_REF_NAME==AES_CBC_128_design_auto_ds_1} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_auto_pc_1/AES_CBC_128_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_auto_pc_1 || ORIG_REF_NAME==AES_CBC_128_design_auto_pc_1} -quiet] -quiet

# IP: bd/AES_CBC_128_design/ip/AES_CBC_128_design_auto_pc_2/AES_CBC_128_design_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_CBC_128_design_auto_pc_2 || ORIG_REF_NAME==AES_CBC_128_design_auto_pc_2} -quiet] -quiet

# XDC: bd/AES_CBC_128_design/AES_CBC_128_design_ooc.xdc
