# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/User/AES_EBC_128_ip_check/AES_EBC_128_ip_check.srcs/sources_1/bd/AES_EBC_128_design/ip/AES_EBC_128_design_axis_data_fifo_0_1/AES_EBC_128_design_axis_data_fifo_0_1.xci
# IP: The module: 'AES_EBC_128_design_axis_data_fifo_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/AES_EBC_128_ip_check/AES_EBC_128_ip_check.srcs/sources_1/bd/AES_EBC_128_design/ip/AES_EBC_128_design_axis_data_fifo_0_1/AES_EBC_128_design_axis_data_fifo_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_EBC_128_design_axis_data_fifo_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/User/AES_EBC_128_ip_check/AES_EBC_128_ip_check.srcs/sources_1/bd/AES_EBC_128_design/ip/AES_EBC_128_design_axis_data_fifo_0_1/AES_EBC_128_design_axis_data_fifo_0_1.xci
# IP: The module: 'AES_EBC_128_design_axis_data_fifo_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/AES_EBC_128_ip_check/AES_EBC_128_ip_check.srcs/sources_1/bd/AES_EBC_128_design/ip/AES_EBC_128_design_axis_data_fifo_0_1/AES_EBC_128_design_axis_data_fifo_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_EBC_128_design_axis_data_fifo_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
